In [3]:
import numpy as np

a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


In [4]:
import time

a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("vectorized version: " + str(1000*(toc-tic)) + "ms ")

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("non-vectorized version: " + str(1000*(toc-tic)) + "ms ")

249770.340253
vectorized version: 12.7708911896ms 


249770.340253
non-vectorized version: 594.842910767ms 


In [5]:
A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[  56.     0.     4.4   68. ]
 [   1.2  104.    52.     8. ]
 [   1.8  135.    99.     0.9]]


In [6]:
cal = A.sum(axis=0)
print(cal)

[  59.   239.   155.4   76.9]


In [7]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[ 94.91525424   0.           2.83140283  88.42652796]
 [  2.03389831  43.51464435  33.46203346  10.40312094]
 [  3.05084746  56.48535565  63.70656371   1.17035111]]


In [8]:
x = np.random.randn(5)  # create rank 1 array  = TRY not to use it!!
print(x)

[ 0.44953188 -1.24527084  0.5626849   0.52294197  1.12573575]


In [9]:
print(x.shape)

(5,)


In [10]:
print(x.T)

[ 0.44953188 -1.24527084  0.5626849   0.52294197  1.12573575]


In [11]:
print(np.dot(a,a.T))

333278.090844


In [14]:
a = np.random.randn(5,1) #column vector  -- or (1,5) - row vector
print(a)

[[-0.15528326]
 [ 0.55733288]
 [ 1.12785336]
 [ 2.44396362]
 [ 0.39351452]]


In [17]:
assert(a.shape == (5,1)) #do this for documentation and make sure all is working properly
print(a.T)

[[-0.15528326  0.55733288  1.12785336  2.44396362  0.39351452]]


In [16]:
print(np.dot(a,a.T))

[[ 0.02411289 -0.08654447 -0.17513674 -0.37950663 -0.06110622]
 [-0.08654447  0.31061994  0.62858976  1.36210128  0.21931858]
 [-0.17513674  0.62858976  1.2720532   2.75643257  0.44382667]
 [-0.37950663  1.36210128  2.75643257  5.97295816  0.96173516]
 [-0.06110622  0.21931858  0.44382667  0.96173516  0.15485367]]
